### ISSUE TITLE
Recalc module: tracking entities

### ISSUE THREAD

**Issue by Aldius** [Aldius/webtechnologiak-re-management-system#14]
Create an API to create, read, update and delete entities present in the data store module (real estate, appraisal).

Recalc module is notified whenever a new entity is created, deleted, or updated and stores the relevant attributes in its own version of the entity.

**Comment by fovecsernyes** [comment]
@pevad95 @Aldius can any of you provide me the paramters of the entity?I have not taken part in the design phase, so I have no idea about the exact data i have to deal with. Thanks

**Comment by fovecsernyes** [comment]
pr is open: https://github.com/Aldius/webtechnologiak-re-management-system/pull/21

**Comment by fovecsernyes** [comment]
merged
